export enum RESPONSE_CODES {
  INVALID_REQUEST = 'ERR_INVALID_REQ',
  INVALID_ADDRESS = 'ERR_INVALID_ADDR',
  INTERNAL_ERROR = 'ERR_INTERNAL_ERROR',
  ADDRESS_NOT_QUALIFY = 'ADDR_NOT_QUALIFY',
  ADDRESS_QUALIFY = 'ADDR_QUALIFY',
}
