import Head from 'next/head'
import Image from 'next/image'
import EnterKuniverse from '../components/EnterKuniverse'
import Header from '../components/Header'
import PlayLikeKun from '../components/PlayLikeKun'
import VideoSection from '../components/VideoSection'
import styles from '../styles/Home.module.css'

export default function Home(): JSX.Element {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <div className={styles.bgWrap}>
          <Image
            alt="Kuniverse Background"
            src="/images/bg-landing.png"
            layout="fill"
            objectFit="cover"
            quality={100}
          />
        </div>
        <div className={styles.heroSection}>
          <div className={styles.logo}>
            <Image
              alt="Kuniverse Logo"
              src="/images/kuniverse-logo.png"
              layout="fixed"
              quality={100}
              width={439}
              height={223}
            />
            <Image
              alt="Sandbox Logo"
              src="/images/sandbox-logo.svg"
              className={styles.sandboxLogo}
              layout="fixed"
              quality={100}
              width={147}
              height={44}
            />
          </div>
        </div>
        <VideoSection />
        <PlayLikeKun />
        <EnterKuniverse />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
